import "./globals.css";
import { NavBar } from "@/Components/NavBar";
import favicon from '@/assets/favicon.svg'
import faviconOrange from '@/assets/favivonOrange.svg'

export const metadata = {
    title: "Davidev Portfolio",
    description: "Generated by create next app",
    icons: {
        icon: "./favicon.svg"
    },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <head>
                <link
                    rel="stylesheet"
                    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
                />
            </head>
            <body className="w-full max-w-7xl mx-auto">
                <NavBar />
                {children}
            </body>
        </html>
    );
}
